### ISSUE TITLE
Body text is difficult to read

### ISSUE THREAD

**Issue by thomasboyt** [orderedlist/minimal#1]
While I really like this theme, I've found the text *very* difficult to read. I know that legibility/readability is a subjective thing, but I'm finding myself straining and leaning forward in my chair so that I can actually see the text. 

Here's two screen shots that show the text being difficult to read - for me, at least, on the couple monitors I have available to view it on - in Chrome:

[OSX](http://f.cl.ly/items/0P2X3J3v1F301f0K313z/Screen%20Shot%202012-04-06%20at%2011.37.53%20PM.png)
[Windows 7](http://i.imgur.com/gxj08.png)

**Comment by beatgammit** [comment]
#2 fixes this with only a subtle change.

**Comment by neuhaus** [comment]
I concur: Please improve the body text color and weight of this theme!

**Comment by orderedlist** [comment]
Thanks for the kick, folks. You're right, this theme got behind. I've updated the contrast, and will put some work into getting the updated version into the GitHub theme picker.

![yes](https://cloud.githubusercontent.com/assets/3073487/5265463/e1e7ede6-7a42-11e4-9bcc-29060188986d.gif)

**Comment by neuhaus** [comment]
Fantastic, thanks!

**Comment by AlexDaniel** [comment]
So https://github.com/orderedlist/minimal/pull/2 made the font darker, but in https://github.com/orderedlist/minimal/commit/3574fcf40f8f3149369ea3d243f23c16196c2b38 it was reverted back to even lighter color (from **#777** to **#727272**). Are you kidding me? There were enough people who went ahead and complained about the problem, and lots of people thumbed up the fix. So why break it? What's going on?

**Comment by orderedlist** [comment]
The weight of Noto Sans is much thicker, and gives more definition. The darker color wasn't as necessary to produce the same amount of contrast. If you'd like to see it darker, I'd be happy to take a look at a PR.

**Comment by neuhaus** [comment]
Thanks for merging PR #25 back in April!

When I create a site using the generator with the minimal theme right now, it **still** has the low contrast and the rgb #727272 color.

When will you roll out this change to the site generator?

**Comment by orderedlist** [comment]
I'm no longer at GitHub, so I can't do this myself, but I'll ping a few people to see if it can get done.

**Comment by neuhaus** [comment]
Thanks. I also emailed github and already got a response that they are looking into it.
