### ISSUE TITLE
Generating from Markdown

### ISSUE THREAD

**Issue by metakermit** [orderedlist/minimal#16]
Hi, I really like the theme and would like to use it, but I don't know how to edit the content in Markdown with it (working directly with HTML is a bit painful). After I created the GitHub page using the generator it just generated the HTML, not the Markdown. I see that you provide the .md source on the demo page, so I assume you do generate it from Markdown. Is there some easy way to integrate this theme with Jekyll or Octopress? Couldn't find anything online.

**Comment by csgillespie** [comment]
A quick comment. "layout:default" didn't work for me, but "layout: default" did.
