### ISSUE TITLE
Readability in with computers with lower DPI

### ISSUE THREAD

**Issue by bluejamesbond** [orderedlist/minimal#17]
I have changed the font to `Noto Sans` and updated some margins and line-heights in order to improve the readability. The demo of your design with the slight modifications can be seen here: http://bluejamesbond.github.io/ExcelQuery/

If you feel that those modifications are helpful, I can make a pull request with the changes.

Thank you very much for the clean design!

**Comment by orderedlist** [comment]
Noto Sans is pretty nice, I've actually updated the theme to use it, along with some other tweaks. Thanks!
