### ISSUE TITLE
code font size in headings

### ISSUE THREAD

**Issue by ousia** [orderedlist/minimal#28]
@orderedlist,

the first heading at http://www.learn-pandoc.tk shows the issue.

The problematic code is the following:

``` css
code, pre {
  font-size:12px;
}
```

Would it be possible that both `code` and `pre` didn’t have a fixed font size?

Otherwise, code in headings looks weird. Even in running text, it looks suboptimal (x-height should be the same).

Many thanks for your help.

**Comment by ousia** [comment]
@orderedlist, any chance of considering this?

I can contribute the pull request myself, but it only makes sense if you want to fix the issue.

**Comment by orderedlist** [comment]
I'd be open to this change, for sure.

**Comment by ousia** [comment]
@orderedlist, many thanks for your reply.

I removed the font size in both elements in the PR above.

**Comment by orderedlist** [comment]
Fixed by #37
